apps/authPro/urls.py
from django.urls import path, re_path, include
from .views import LoginView, register_view, logout_view, graph_captcha, aboutme_view, updatepsd_view


app_name = 'authPro'

urlpatterns = [
    path('login/', LoginView, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('graph-captcha/', graph_captcha, name='graph_captcha'),
    path('aboutme/', aboutme_view, name='aboutme'),
    path('updatepsd/', updatepsd_view, name='updatepsd'),
]

apps/conn/urls.py
from django.urls import path, re_path, include
from .views import connect_dis_view, connect_edit_view, connect_detail_view, NewsPub, news_list, del_my_news, add_comment, comment_with_news, search_view, my_pub_view

app_name = 'connApp'

urlpatterns = [
    path('dis/', connect_dis_view, name='display'),
    path('my-pub/', my_pub_view, name='my-pub'),
    path('edit/', connect_edit_view, name='edit'),
    path('detail/<int:news_id>/', connect_detail_view, name='detail'),
    path('news-pub/', NewsPub.as_view(), name='pub'),
    path('list/', news_list, name='news_list'),
    path('del_my_new/',del_my_news, name='del_my_new'),
    path('add_comment/',add_comment, name='add_comment'),
    path('comment/list/', comment_with_news, name='comment_list'),
    path('search/', search_view, name='search'),

]

apps/position/urls.py
from django.urls import path, re_path, include
from .views import get_pos, search_key_view, select_points, index, search, analyze, count_city, other, charCity, charXueli, charWorkJy, charWorkIndustry, charWorkSize, get_data_list, get_word_view

# 防止不同app中的URL的name产生冲突   reverse(appName:hello)
app_name = 'position'

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('get_pos/', get_pos, name='get_pos'),
    path('search_key/', search_key_view, name='search_key'),
    path('select_points/', select_points, name='select_points'),
    path('analyze/', analyze, name='analyze'),
    path('count_city/', count_city, name='count_city'),
    path('other/', other, name='other'),
    path('charCity/', charCity, name='charCity'),
    path('charXueli/', charXueli, name='charXueli'),
    path('charWorkJy/', charWorkJy, name='charWorkJy'),
    path('charWorkIndustry/', charWorkIndustry, name='charWorkIndustry'),
    path('charWorkSize/', charWorkSize, name='charWorkSize'),
    path('get_data_list/', get_data_list, name='get_data_list'),
    path('get_word_cloud/', get_word_view, name='get_word_cloud'),
]

lagou_position/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# 要放在/ 路由  要么你就在把URL 定义成 /admin/media/

urlpatterns = [
    path('', include('apps.position.urls')),
    # path('position/', include('apps.position.urls')),
    path('auth/', include('apps.authPro.urls')),
    path('conn/', include('apps.conn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base_top.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Base{% endblock %}</title>
    <link rel="shortcut icon " type="images/x-icon" href="../../static/images/ico.ico">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css" />
    <link href="http://api.map.baidu.com/library/IndoorMap/1.0/src/indoor.min.css?v=1.0.1 " rel="stylesheet" type="text/css">
{#    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">#}
    <link href="{% static 'css/base/bootstrap-3.3.7/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static '/css/base/sweetalert.css' %}">

    <link rel="stylesheet" href="{% static 'css/base/base_top.css' %}">
    {% block link %}

    {% endblock %}
</head>


<body>

<!-- header start -->
{% block header %}
<header id="header">

    <nav class="navbar navbar-default navbar-fixed-top" id="nav-top">

        <div class="container-fluid">
{#            logo#}
            <div class="navbar-header">
              <a class="navbar-brand" href="#">智慧职位搜索展示系统</a>
            </div>
{#          navbar-right   导航#}
            <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-8">
                <ul class="nav navbar-nav navbar-left">
                  <li class="haha" id="t_index"><a href="{% url 'position:index' %}">职位首页</a></li>
                  <li class="haha" id="t_analyze"><a href="{% url 'position:analyze' %}">统计分析</a></li>
                  <li class="haha" id="t_connect"><a href="{% url 'connApp:display' %}">求职交流</a></li>
{#                  <li class="haha" id="t_other"><a href="{% url 'position:other' %}">其他</a></li>#}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.session.is_login %}
{#                        如果用户登录#}
{#                        <img src="{{ request.session.user_avatar.url }}" style="max-width: 20%; border-radius: 15%;"/>#}
                        <li class="dropdown" style="display: inline-block">
{#                        头像#}
                            <a href="" id="is_me" class="dropdown-toggle" data-toggle="dropdown">{{ request.session.user_name }} <span class="caret"></span></a>
                            <ul class="dropdown-menu" >
                                <li><a href="{% url 'authPro:aboutme' %}">我的资料</a></li>
                                <li><a href="#">...</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'authPro:logout' %}">退出登录</a></li>
                            </ul>
                        </li>
                    {% else %}
{#                        用户没登录#}
                        <li><a href="{% url 'authPro:register' %}"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
                        <li><a href="{% url 'authPro:login' %}"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
                    {% endif %}
                </ul>

            </div>
          </div>
    </nav>

</header>
<!-- header end -->
{% endblock %}




{#主体#}
{% block content %}
{% endblock %}







<script src="{% static 'js/base/jquery-3.3.1.js' %}"></script>
<script src="{% static 'js/base/bootstrap-3.3.7/bootstrap.js' %}"></script>
<script src="{% static 'js/position/echarts.js' %}"></script>
<script src="{% static 'js/fontawesome.js' %}"></script>

<script src="{% static 'js/base/sweetalert.min.js' %}"></script>
<script src="{% static 'js/base/fsweetalert.js' %}"></script>
<script src="{% static 'js/base/setup.js' %}"></script>
<script src="{% static 'js/base/message.js' %}"></script>
<script src="{% static 'js/base/common.js' %}"></script>
<script src="{% static 'js/base/base_top.js' %}"></script>

<!-- 加载地图JSAPI脚本 -->
<script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=A413DT59OvGqxFLVIukjSFyfQoE327kz"></script>
<script type="text/javascript" src="//api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js"></script>
<script type="text/javascript" src="//api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js"></script>
<script type="text/javascript" src="//api.map.baidu.com/library/MarkerClusterer/1.2/src/MarkerClusterer_min.js"></script>
<script type="text/javascript" src="http://developer.baidu.com/map/custom/stylelist.js"></script>


{% block script %}
{% endblock %}




</body>
</html>