apps/conn/urls.py
from django.urls import path, re_path, include
from .views import connect_dis_view, connect_edit_view, connect_detail_view, NewsPub, news_list, del_my_news, add_comment, comment_with_news, search_view, my_pub_view

app_name = 'connApp'

urlpatterns = [
    path('dis/', connect_dis_view, name='display'),
    path('my-pub/', my_pub_view, name='my-pub'),
    path('edit/', connect_edit_view, name='edit'),
    path('detail/<int:news_id>/', connect_detail_view, name='detail'),
    path('news-pub/', NewsPub.as_view(), name='pub'),
    path('list/', news_list, name='news_list'),
    path('del_my_new/',del_my_news, name='del_my_new'),
    path('add_comment/',add_comment, name='add_comment'),
    path('comment/list/', comment_with_news, name='comment_list'),
    path('search/', search_view, name='search'),

]

lagou_position/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# 要放在/ 路由  要么你就在把URL 定义成 /admin/media/

urlpatterns = [
    path('', include('apps.position.urls')),
    # path('position/', include('apps.position.urls')),
    path('auth/', include('apps.authPro.urls')),
    path('conn/', include('apps.conn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/connect/connect.html
{% extends 'base/base_top.html' %}
{% load news_filter %}

{% block title %}  求职交流 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="{% static 'css/connect/conn.css' %}">
{%  endblock %}



{%  block content %}


<div class="container">
   <div class="row">
       <!--左边部分-->
       <div class="col-md-2">
       </div>

       <!--中间部分-->
       <div class="col-md-7">
                    <!-- news-contain start -->
        <div class="news-contain">
              <ul class="news-list">
                    {% for new in newses %}
                      <li class="news-item" >
                          <div class="news-content">
                                <h4 class="news-title"><a href="{% url 'connApp:detail' news_id=new.id %}" target="_blank">{{ new.title }}</a></h4>
                                <p class="news-details">{{ new.content }}</p>
                                <div class="news-other">
                                      <span class="news-time">{{ new.pub_time}}</span>
                                      <span class="news-author">{{ new.author.username }}</span>
                                </div>
                          </div>
                    </li>
                    {% endfor %}
              </ul>
        </div>
        <!-- news-contain end -->
        <!-- btn-more start -->
        <a href="javascript:void(0);" class="btn-more" data-page="2">加载更多</a>
        <!-- btn-more end -->

       </div>

       <!--右边部分-->
       <div class="col-md-3">
           <!-- /input-group -->
{#           <form class="form-group">#}
{#               <input type="text" class="form-control search_in" style="height: 34px" placeholder="搜索文章...">#}
{#               <span class="input-group-btn">#}
{#                   <button class="btn btn-danger search_news" type="button" ><a href="{% url 'connApp:display' %}"></a>搜索</button>#}
{#               </span>#}
{#           </form>#}

           <form class="form-inline" style="min-width: 1200px" method="get" action="{% url 'connApp:search' %}" target="_blank">
              <div class="form-group">
                <div class="input-group">
                  <input type="text" class="form-control " name="q" style="height: 34px; width: 201px;"  placeholder="搜索文章...">
                </div>
              </div>
              <button type="submit" class="btn btn-danger">搜索</button>
            </form>




           <div class="row danger-info">
               <div class="col-md-6">
                   <button class="btn btn-info pull-left"><a href="{% url 'connApp:edit' %}" style="color: white">发表动态</a></button>
               </div>
               <div class="col-md-6 news_mine">
                    <button class="btn btn-success pull-right"><a href="{% url 'connApp:my-pub' %}" style="color: white" target="_blank">我的文章</a></button>
               </div>
           </div>


       </div>
   </div>


</div>

{#<div class="row footer" style="bottom: 5px; position: absolute; margin-left: 40%">Copyright©2019-2020 薛彭帅 All Rights Reserved</div>#}

{% endblock %}





{% block script %}
    <script src="{% static 'js/connect/connect.js' %}"></script>
{%  endblock %}

templates/connect/edit.html
{% extends 'base/base_top.html' %}

{% block title %}  编辑信息 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="{% static 'css/connect/edit.css' %}">
{%  endblock %}




{%  block content %}

<div class="row">
    <div class="col-md-8 col-xs-8 col-sm-8 col-md-offset-2">
      <div class="box box-primary">
        <div class="box-body">
          <div class="form-group">
            <label for="news-title">标题</label>
            {% if news %}
                <input type="text" class="form-control" id="news-title" name="news-title" placeholder="请输入文章标题" value="{{ news.title }}">
                {% else %}
                <input type="text" class="form-control" id="news-title" name="news-title" placeholder="请输入文章标题" autofocus>
            {% endif %}
          </div>

          <div class="form-group">
            <label for="news-content">内容</label>
              {% if news %}
                  <div id="edit_div"></div>
                  <script>
                  window.onload = function () {
                      window.editor.txt.html('{{ news.content|safe }}');
                  }
                  </script>
                  {% else %}
                  <div id="edit_div"></div>
              {% endif %}
          </div>

        </div>
        <div class="box-footer">
          <button class="btn btn-danger"><a id="back_it" href="{% url 'connApp:display' %}" style="color: white"> &lt;&lt;&nbsp;返回</a></button>

          <a href="javascript:void (0);" class="btn btn-primary pull-right btn-pub-news" data-news-id="{{ news.id }}">
              {% if news %}
                    更新动态
                  {% else %}
                    发布动态
              {% endif %}
          </a>
        </div>
      </div>
    </div>
</div>




{% endblock %}





{% block script %}

    <script src="{% static 'js/base/wangEditor.js' %}"></script>
    <script src="{% static 'js/base/xss.js' %}"></script>
    <script src="{% static 'js/connect/edit.js' %}"></script>
{%  endblock %}

templates/connect/my_pub.html
{% extends 'base/base_top.html' %}
{% load news_filter %}

{% block title %}  我的文章 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="{% static 'css/connect/conn.css' %}">
{%  endblock %}



{%  block content %}


<div class="container">
   <div class="row">
       <!--左边部分-->
       <div class="col-md-2">
       </div>

       <!--中间部分-->
       <div class="col-md-7">
                    <!-- news-contain start -->
        <div class="news-contain">
              <ul class="news-list">
                    {% for new in newses %}
                      <li class="news-item" >
            {#              # 过滤器传参#}
                          <div class="news-content">
                                <h4 class="news-title"><a href="{% url 'connApp:detail' news_id=new.id %}" target="_blank">{{ new.title }}</a></h4>
                                <p class="news-details">{{ new.content }}</p>
                                <div class="news-other">
                                      <span class="news-time">{{ new.pub_time}}</span>
                                      <span class="news-author">{{ new.author.username }}</span>
                                </div>
                          </div>
                    </li>
                    {% endfor %}
              </ul>
        </div>
        <!-- news-contain end -->
        <!-- btn-more start -->
        <a href="javascript:void(0);" class="btn-more" data-page="2">加载更多</a>
        <!-- btn-more end -->

       </div>

       <!--右边部分-->
       <div class="col-md-3">
       </div>
   </div>


</div>

{#<div class="row footer" style="bottom: 5px; position: absolute; margin-left: 40%">Copyright©2019-2020 薛彭帅 All Rights Reserved</div>#}

{% endblock %}





{% block script %}
    <script src="{% static 'js/connect/my_pub.js' %}"></script>
{%  endblock %}

templates/connect/news_detail.html
{% extends 'base/base_top.html' %}

{% block title %} 文章【{{ news.title }}】 详情 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="{% static 'css/connect/detail.css' %}">
{%  endblock %}



{%  block content %}

<!--main start-->
<main id="main">
  <div class="w800 clearfix">
    <!-- news-contain start  -->
    <div class="news-contain">
      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info" nid="{{ news.id }}" id="nidid">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.pub_time   }}</span>
            {% if news.author.id == session_user_id  %}
                <span class="del-myself-new">删除</span>
            {% endif %}

        </div>
      </div>
      <article class="news-content">
{#         safe  转义 =》带样式   #}
        {{ news.content |safe }}
      </article>
      <div class="comment-contain">
        <div class="comment-pub clearfix">
          <div class="new-comment">
            文章评论(<span class="comment-count">0</span>)
          </div>
            {% if request.session.is_login %}
                <div class="comment-control logged-comment">
                    <input type="text" placeholder="请填写评论">
                </div>
                {#            可以给他加一个 data-news-id 可以直接在前端获取这个值来获取当前news的id#}
                <button class="comment-btn" data-news-id="{{ news.id }}">发表评论</button>
            {% else %}
                <div class="comment-control please-login-comment" style="display:block;">
                    <input type="text" placeholder="请登录后参加评论" readonly>
                </div>
            {% endif %}

        </div>
{#      评论区#}
        <ul class="comment-list">
        </ul>
      </div>

    </div>
    <!-- news-contain end  -->

  </div>
</main>
<!-- main end -->

{% endblock %}





{% block script %}
    <script src="{% static 'js/base/xss.js' %}"></script>
    <script src="{% static 'js/connect/detail.js' %}"></script>
{%  endblock %}

templates/connect/search.html
{% extends 'base/base_top.html' %}
{% load news_filter %}

{% block title %}  搜索结果 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="{% static 'css/connect/conn.css' %}">
{%  endblock %}



{%  block content %}


<div class="container">
   <div class="row">
       <!--左边部分-->
       <div class="col-md-2">
       </div>

       <!--中间部分-->
       <div class="col-md-7">
                    <!-- news-contain start -->
        <div class="news-contain">
              <ul class="news-list" s_k = "{{ s_key }}">
                    {% for new in newses %}
                      <li class="news-item" >
            {#              # 过滤器传参#}
                          <div class="news-content">
                                <h4 class="news-title"><a href="{% url 'connApp:detail' news_id=new.id %}" target="_blank">{{ new.title }}</a></h4>
                                <p class="news-details">{{ new.content }}</p>
                                <div class="news-other">
                                      <span class="news-time">{{ new.pub_time}}</span>
                                      <span class="news-author">{{ new.author.username }}</span>
                                </div>
                          </div>
                    </li>
                    {% endfor %}
              </ul>
        </div>
        <!-- news-contain end -->
        <!-- btn-more start -->
        <a href="javascript:void(0);" class="btn-more" data-page="2">加载更多</a>
        <!-- btn-more end -->

       </div>

       <!--右边部分-->
       <div class="col-md-3">
       </div>
   </div>

</div>

{#<div class="row footer" style="bottom: 5px; position: absolute; margin-left: 40%">Copyright©2019-2020 薛彭帅 All Rights Reserved</div>#}

{% endblock %}





{% block script %}
    <script src="{% static 'js/connect/search.js' %}"></script>
{%  endblock %}