apps/position/urls.py
from django.urls import path, re_path, include
from .views import get_pos, search_key_view, select_points, index, search, analyze, count_city, other, charCity, charXueli, charWorkJy, charWorkIndustry, charWorkSize, get_data_list, get_word_view

# 防止不同app中的URL的name产生冲突   reverse(appName:hello)
app_name = 'position'

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('get_pos/', get_pos, name='get_pos'),
    path('search_key/', search_key_view, name='search_key'),
    path('select_points/', select_points, name='select_points'),
    path('analyze/', analyze, name='analyze'),
    path('count_city/', count_city, name='count_city'),
    path('other/', other, name='other'),
    path('charCity/', charCity, name='charCity'),
    path('charXueli/', charXueli, name='charXueli'),
    path('charWorkJy/', charWorkJy, name='charWorkJy'),
    path('charWorkIndustry/', charWorkIndustry, name='charWorkIndustry'),
    path('charWorkSize/', charWorkSize, name='charWorkSize'),
    path('get_data_list/', get_data_list, name='get_data_list'),
    path('get_word_cloud/', get_word_view, name='get_word_cloud'),
]

lagou_position/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# 要放在/ 路由  要么你就在把URL 定义成 /admin/media/

urlpatterns = [
    path('', include('apps.position.urls')),
    # path('position/', include('apps.position.urls')),
    path('auth/', include('apps.authPro.urls')),
    path('conn/', include('apps.conn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/position/models.py
from django.db import models

# ['公司全名', '公司简称', '公司规模', '融资阶段', '区域', '职位名称', '工作经验',
# '学历要求', '薪资', '职位福利', '经营范围','职位类型', '公司福利', '第二职位类型', '城市', '纬度', '经度')


class Position(models.Model):

    fullname = models.CharField(max_length=50)         # 公司全名
    name = models.CharField(max_length=50)              # 公司简称
    size = models.CharField(max_length=20)              # 公司规模
    rzjd = models.CharField(max_length=20)              # 融资规模
    area = models.CharField(max_length=30)              # 城市的街区
    zwname = models.CharField(max_length=30)           # 职位名称
    gzjy = models.CharField(max_length=20)              # 工作经验
    xueli = models.CharField(max_length=30)             # 学历
    money = models.CharField(max_length=30)             # 薪资（月薪）
    zwfl = models.CharField(max_length=100)             # 职位诱惑      "年底多薪 技术大牛 学术氛围好 成长迅速"
    jyfanwei = models.CharField(max_length=30)         # 领域/ 经营范围
    zwtype = models.CharField(max_length=50)           # "开发|测试|运维类"
    gsfl = models.CharField(max_length=100)             # ["弹性工作", "领导好", "扁平管理", "五险一金"]
    drzwjy = models.CharField(max_length=20)            # "人工智能" / 后端开发
    city = models.CharField(max_length=20)              # 城市
    lat = models.CharField(max_length=20)               # 纬度
    lon = models.CharField(max_length=20)              # 经度
    detail_link = models.CharField(max_length=50)      # 职位详情链接
    user_id = models.IntegerField(null=True)  # 所属的用户
    city_count = models.IntegerField(null=True)         # 城市数量

    def __str__(self):
        return str(("{},{},{},{},{},{}".format(self.name, self.money, self.zwtype, self.city, self.lat, self.lon)))

apps/position/views.py
import json
import time
import requests
import jieba
from django.db.models import Q
from wordcloud import WordCloud
import PIL.Image as image
import numpy as np

from lagou_position.settings import MEDIA_ROOT  as media_path
from lagou_position.settings import STATICFILES_DIRS as static_path

from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse,JsonResponse
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.views.generic import View
from django.http import Http404
from django.views.decorators.http import require_GET, require_POST
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core import serializers

from utils import mcache
from .models import Position
from .pa import PaPosition

from django.db import connection



# 首页
# @csrf_protect
# @login_required
def index(request):
    username = request.session.get('user_name', '')
    if not username:
        return redirect('/auth/login/')
    else:
        return render(request, 'position/index.html')


# @csrf_protect
# 获取点位置
def get_pos(request):
    if request.method == 'POST':
        positions = Position.objects.filter(user_id=request.session.get('user_id'))
        position_res = serializers.serialize('json', positions)  # 讲查询结果json序列化
        # print(position_res)
        return HttpResponse(position_res, content_type="application/json")   # 职位数据json
    else:
        # return JsonResponse({'data': 'error!'})
        pass


# 首页 职位列表筛选 like
def search_key_view(request):
    if request.method == 'POST':
        parm = request.POST.get('params')
        positions = Position.objects.filter(user_id=request.session.get('user_id')).filter(Q(name__icontains=parm) | Q(size__icontains=parm) | Q(zwname__icontains=parm) | Q(xueli__icontains=parm) | Q(gzjy__icontains=parm) | Q(city__icontains=parm))
        position_res = serializers.serialize('json', positions)  # 讲查询结果json序列化
        # print(position_res)
        return HttpResponse(position_res, content_type="application/json")   # 职位数据json
    else:
        # return JsonResponse({'data': 'error!'})
        pass


# 筛选地图点,联动
def select_points(request):
    if request.method == 'POST':
        parm = request.POST.get('params')
        type_name = request.POST.get('typeName')

        if type_name == "学历":
            positions = Position.objects.filter(xueli=parm, user_id=request.session.get('user_id'))
        elif type_name == "经验":
            positions = Position.objects.filter(gzjy=parm, user_id=request.session.get('user_id'))
        elif type_name == "城市":
            positions = Position.objects.filter(city=parm, user_id=request.session.get('user_id'))
        elif type_name == "领域":
            positions = Position.objects.filter(jyfanwei=parm, user_id=request.session.get('user_id'))
        elif type_name == "规模":
            positions = Position.objects.filter(size=parm, user_id=request.session.get('user_id'))

        position_res = serializers.serialize('json', positions)  # 讲查询结果json序列化
        print(position_res)
        return HttpResponse(position_res, content_type="application/json")   # 职位数据json
    else:
        pass


# 分析页面职位列表的筛选
def get_data_list(request):
    if request.method == 'POST':
        parm = request.POST.get('parm')
        typeName = request.POST.get('typeName')

        if typeName == "学历":
            positions = Position.objects.filter(xueli=parm, user_id=request.session.get('user_id'))
        elif typeName == "经验":
            positions = Position.objects.filter(gzjy=parm, user_id=request.session.get('user_id'))
        elif typeName == "城市":
            positions = Position.objects.filter(city=parm, user_id=request.session.get('user_id'))
        elif typeName == "领域":
            positions = Position.objects.filter(jyfanwei=parm, user_id=request.session.get('user_id'))
        elif typeName == "规模":
            positions = Position.objects.filter(size=parm, user_id=request.session.get('user_id'))

        position_res = serializers.serialize('json', positions)  # 将查询结果json序列化
        return HttpResponse(position_res, content_type="application/json")   # 职位数据json


# 获取代理
def get_proxy():
    # 111.206.217.186:8082
    return requests.get("http://127.0.0.1:5010/get/").json().get("proxy")

def delete_proxy(proxy):
    requests.get("http://127.0.0.1:5010/delete/?proxy={}".format(proxy))


# 点击爬取职位信息
def search(request):
    if request.method == "POST":
        canshu = request.POST.get('zname')
        # run: pa function
        # ......
        try:

            # 先判断数据表原来有没有数据
            result = Position.objects.filter(user_id=request.session.get('user_id'))
            if result.exists():
                print("用户id：" + str(request.session.get('user_id')) + " : QuerySet has Data, 先清除原来数据,再进行导入...")  # 清空用户原来数据
                Position.objects.filter(user_id=request.session.get('user_id')).delete()

            url = " https://www.lagou.com/jobs/positionAjax.json?needAddtionalResult=false"
            proxie = {"http": "http://{}".format(get_proxy())}
            pa = PaPosition(canshu, request.session['user_id'], proxies=proxie)
            # 用户输入的参数
            first_page = pa.get_json(url, 1, canshu)  # 先获取第一页数据
            total_page_count = first_page['content']['positionResult']['totalCount']  # 职位总数
            num = pa.get_page_num(total_page_count)  # 页码数
            total_info = []
            time.sleep(1)
            print("{0}相关职位总数:{1},总页数为:{2}".format(canshu, total_page_count, num))
            # 正式开始
            for num in range(1, num + 1):
                # 每一轮都更换代理
                pa.proxies = {"http": "http://{}".format(get_proxy())}
                print("代理： " + str( pa.proxies))
                # 获取【每一页】的职位相关的信息
                page_data = pa.get_json(url, num, canshu)  # 获取响应json
                jobs_list = page_data['content']['positionResult']['result']  # 获取每页的所有gis相关的职位信息
                page_info = pa.get_page_info(jobs_list)
                # print("每一页python相关的职位信息:%s" % page_info, '\n\n')
                total_info += page_info
                print('已经爬取到第{}页，职位总数为{}'.format(num, len(total_info)))
                time.sleep(1)

                print("OK!")
        except Exception as e:
            print("Error     :   \n")
            print(e)
            jsonData = {
                "stat": "error",
            }
            return JsonResponse(jsonData)

        print("任务完成!!!")

        jsonData = {
            "stat": "success",
        }
        return JsonResponse(jsonData)



# @csrf_protect
# 图表展示职位分析
# @login_required
def analyze(request):
    username = request.session.get('user_name', '')
    # 如果没有登录
    if not username:
        return redirect('/auth/login/')
    else:
        return render(request, 'position/analyze.html')


# 统计城市职位数量  （热力图用的）
def count_city(request):
    if request.method == "POST":
        successData = {
            "stat": "success",
        }
        failData = {
            "stat": "fail",
        }
        city_dict = {}
        try:
            city_counts = Position.objects.filter(user_id=request.session.get('user_id')).values('city')
            for i in city_counts:
                if i['city'] in city_dict:
                    count = city_dict[i['city']]
                else:
                    count = 0
                count = count + 1
                city_dict[i['city']] = count
                # print(i.value())
            all_data = Position.objects.filter(user_id=request.session.get('user_id'))
            # print(all_data)
            for j in all_data:
                # print(j.city)
                if j.city in city_dict.keys():  # 判断sql查出来的city, 是否在字典的key中
                    # 查出数据,update他的count的值为对应字典键值对的value
                    # 如果在，就更新数据
                    Position.objects.filter(id=j.id, user_id=request.session.get('user_id')).update(city_count=city_dict[j.city])
            # print(city_dict)
            # print("更新count_city完成!")
        except Exception as e:

            return JsonResponse(failData)
        else:
            return JsonResponse(successData)


# 测试
def other(request):
    # print(type(request.session['user_id']))
    return render(request, 'position/other.html')


# 统计图 char city
def charCity(request):
    if request.method == "POST":
        qResult = Position.objects.filter(user_id=request.session.get('user_id')).values("city", "city_count").distinct().order_by('-city_count')  # 去重,并且从大到小排序
        cityList = list(qResult)   # 直接把QuerySet转为List
        # print(len(cityList))
        return HttpResponse(json.dumps({'data': cityList}), content_type="application/json")


# 统计图  char 学历
# select xueli,count(*) from position_position group by xueli;
def charXueli(request):
    if request.method == "POST":
        cursor = connection.cursor()
        sql = "select xueli,count(*) as x_count from position_position where user_id="+str(request.session.get('user_id')) + " group by xueli"
        cursor.execute(sql)
        x_dict = dict(list(cursor.fetchall()))
        # print(x_dict)
        # print(qResult)
        return HttpResponse(json.dumps({'data': x_dict}), content_type="application/json")


# 统计图  char 工作经验
# select xueli,count(*) from position_position group by xueli;
def charWorkJy(request):
    if request.method == "POST":
        cursor = connection.cursor()
        sql = "select gzjy, count(*) as j_count from position_position where user_id="+str(request.session.get('user_id')) + " group by gzjy;"
        # print(sql)
        cursor.execute(sql)
        j_dict = dict(list(cursor.fetchall()))
        # print(j_dict)

        # print(qResult)
        return HttpResponse(json.dumps({'data': j_dict}), content_type="application/json")

# 统计图 pie  行业领域
def charWorkIndustry(request):
    if request.method == "POST":
        cursor = connection.cursor()

templates/position/analyze.html
{% extends 'base/base_top.html' %}

{% block title %}  统计分析 {% endblock %}

{% block link %}
        <link rel="stylesheet" href="../../static/css/analyze.css">
{%  endblock %}




{%  block content %}
    {#城市柱状图#}
    {#工作经验饼图#}
    {#学历饼图#}
    {#词云#}
    {#工资图#}

    <div id="alertmessage"></div>

{#    <div class="top" id="top">#}
{#        <div style="width: 100%; height: 70px" id="iframepage" name="iframepage" ></div>#}

    <div class="showMain">
        <!-- 加载地图 -->
        <div class="map" id="mapholder">
            <div  id="qf" onclick="">
                <i class="toolicon icon-quanfu" ></i>
            </div>
        </div>


        <div class="caseInfoChart showMainModel" id="xueli"></div>

        <div class="caseWordCloud showMainModel">
            <div id="wordCloudImg" class="plugin">
            </div>
        </div>

        <div class="monthCaseChart showMainModel" id="city"></div>

        <div class="admRegMonthCase showMainModel" id="id_size" style="padding-left: 10px;"></div>

        <div class="monitorShowInfo showMainModel" id="jingyan"></div>

        <div class="weekCaseRate showMainModel" id="id_industry"></div>




    <!--         修改弹窗开始 -->
{#		    <%--职位信息--%>#}
    <div class="showCase1 showCase">

        <div class="showCaseInfo container" style="">
            <div class="showCaseInfoMain">
				<div class="row">
				 <div class="col-md-12 caseList" >职位列表
				 <img src="{% static 'images/position/fold.png' %}" alt="图片未找到!" title="展开" id="upAndD">

				 <span style="display:inline-block; float:right; cursor:pointer" id="closeList">X</span>
				  </div>

				</div>

                <div class="row">
                    <div class="col-md-12" style="width: 909px;padding-right: 0px;">
                        <table id = "theadAndTbody" class="table">
                            <thead>  <tr><th>职位</th><th>公司</th><th>城市</th><th>薪资</th><th>学历</th><th>经验</th> <th>详情</th></tr>  </thead>
                            <tbody>
                                <tr> <td></td> <td></td><td></td><td>查询数据为空!</td>  <td></td> <td></td> <td></td> </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

<!-- 修改弹窗结束 -->





        </div>

{#    </div>#}


{% endblock %}





{% block script %}
    <script src="{% static 'js/js2wordcloud/dist/js2wordcloud.min.js' %}"></script>
    <script src="{% static 'js/position/analyze.js' %}"></script>

{%  endblock %}

templates/position/index.html
{% extends 'base/base_top.html' %}

{% block title %}  主页 {% endblock %}

{% block link %}
    <link rel="stylesheet" href="../../static/css/position.css">
 {% endblock %}




{% block content %}

<!--Loading-->
<section class="Loading"></section>
<!--Loading-->

<div class="left_wrapper">
    <form class="form-inline" style="position: relative; top: 50px; left: -15px;" id="pa_form">
      <div class="form-group">
        <label for="zw_name">Search</label>
        <input type="text" class="form-control" id="zw_name" placeholder="搜索...">
      </div>
    </form>

    <button type="button" class="btn btn-success" id="btnPa">爬取数据</button>
    <button type="button" class="btn btn-info" id="btnDis">展示数据</button>
    <button type="button" class="btn btn-danger" id="btnXuan">渲染数据</button>
</div>


{# 百度地图容器 #}
        <div class="out_map">
            <div id="container"></div>
        </div>

        <!--  职位列表开始 -->
        <div class="staTu">
            <div class="staTuMini text-center">
                <i class="fa fa-2x fa-chevron-up" title="展开/隐藏"></i>
            </div>
{#            <%--表格容器--%>#}
            <div class="alSta col-md-12">
                <div class="alStaCon">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="搜索职位..." id="searchName">
                    </div>
                 <span id="id_span"> 职位列表 </span>
                  <div id="id_list_con">
                        <div class="row">
                            <div class="col-md-12" style="padding-right: 0;">
                                <table id = "theadAndTbody" class="table">
                                    <thead>
                                        <tr><th>职位</th><th>公司</th><th>城市</th><th>薪资</th><th>学历</th><th>经验</th> <th>详情</th></tr>
                                    </thead>
                                    <tbody>
                                        <tr> <td></td> <td></td><td></td><td>查询数据为空!</td>  <td></td> <td></td> <td></td> </tr>
                                    </tbody>
                                    <tbody>
                                </table>
                            </div>
                        </div>
                  </div>
                </div>
            </div>
        </div>



{#    test end#}


{% endblock %}

{% block script %}
    <script src="../../static/js/position/position.js"></script>
{% endblock %}






















{#<!doctype html>#}
{#<html>#}
{#<head>#}
{#    <meta charset="utf-8">#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <title>职位地图</title>#}
{##}
{#    <link rel="shortcut icon " type="images/x-icon" href="../../static/images/ico.ico">#}
{#    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">#}
{#    <link rel="stylesheet" href="https://a.amap.com/jsapi_demos/static/demo-center/css/demo-center.css" />#}
{#    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">#}
{#    <link href="http://api.map.baidu.com/library/IndoorMap/1.0/src/indoor.min.css?v=1.0.1 " rel="stylesheet" type="text/css">#}
{#     <link rel="stylesheet" href="../../static/css/position.css">#}
{#    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>#}
{#        <!-- 加载地图JSAPI脚本 -->#}
{#    <script type="text/javascript" src="//api.map.baidu.com/api?v=2.0&ak=A413DT59OvGqxFLVIukjSFyfQoE327kz"></script>#}
{#    <script type="text/javascript" src="//api.map.baidu.com/library/Heatmap/2.0/src/Heatmap_min.js"></script>#}
{#    <script type="text/javascript" src="//api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js"></script>#}
{#	<script type="text/javascript" src="//api.map.baidu.com/library/MarkerClusterer/1.2/src/MarkerClusterer_min.js"></script>#}
{#    <script src="../../static/js/position/position.js"></script>#}
{##}
{##}
{#    <style>#}
{#    </style>#}
{#</head>#}
{#<body>#}
{##}
{#头部#}
{#<nav class="navbar navbar-default navbar-static-top" id="header">#}
{#    <div class="container-fluid">#}
{##}
{#        <div class="navbar-header">#}
{##}
{#          <a class="navbar-brand" href="#">智慧职位展示系统</a>#}
{#        </div>#}
{##}
{#        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">#}
{##}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a href="#"><span class="glyphicon glyphicon-user"></span> 注册</a></li>#}
{#                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>#}
{#            </ul>#}
{##}
{#            <ul class="nav navbar-nav navbar-right">#}
{#              <li class="active haha"><a href="#">职位首页</a></li>#}
{#              <li class="haha"><a href="#">探索</a></li>#}
{#              <li class="haha"><a href="{% url 'position:analyze' %}">统计分析</a></li>#}
{#              <li class="haha"><a href="{% url 'position:other' %}">其他</a></li>#}
{#            </ul>#}
{##}
{##}
{##}
{##}
{#        </div>#}
{#      </div>#}
{#</nav>#}






{#<!--Loading-->#}
{#<section class="Loading"></section>#}
{#<!--Loading-->#}
{##}
{#<div class="left_wrapper">#}
{##}
{#                  <form class="form-inline" style="display: block; margin-top: 60px;margin-left: 37px">#}
{#                  <div class="form-group">#}
{#                    <input type="text" class="form-control" id="zw_name" placeholder="搜索..." size="10">#}
{#                  </div>#}
{#               </form>#}
{#    <form class="form-inline" style="position: relative; top: 40px; left: 5px;">#}
{#      <div class="form-group">#}
{#        <label for="zw_name">Search</label>#}
{#        <input type="text" class="form-control" id="zw_name" placeholder="搜索...">#}
{#      </div>#}
{#    </form>#}
{##}
{#    <button type="button" class="btn btn-success" id="bbb">爬取数据</button>#}
{#    <button type="button" class="btn btn-info" id="ccc">展示数据</button>#}
{#    <button type="button" class="btn btn-danger" id="ddd">渲染数据</button>#}
{#    #}
{#</div>#}
{##}
{#<div id="container">#}
{#    <div id="container"></div>#}
{##}
{#</div>#}
{##}
{#<div id="container"></div>#}

{##}
{##}
{##}
{#</body>#}
{#</html>#}

templates/position/other.html
{% extends 'base/base_top.html' %}

{% block title %}  other {% endblock %}

{#{% block link %}#}
{#{%  endblock %}#}




{%  block content %}


    <div id="map_div"></div>

{% endblock %}





{% block script %}
    <script src="{% static 'js/position/other.js' %}"></script>
{%  endblock %}