apps/authPro/urls.py
from django.urls import path, re_path, include
from .views import LoginView, register_view, logout_view, graph_captcha, aboutme_view, updatepsd_view


app_name = 'authPro'

urlpatterns = [
    path('login/', LoginView, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('graph-captcha/', graph_captcha, name='graph_captcha'),
    path('aboutme/', aboutme_view, name='aboutme'),
    path('updatepsd/', updatepsd_view, name='updatepsd'),
]

apps/position/urls.py
from django.urls import path, re_path, include
from .views import get_pos, search_key_view, select_points, index, search, analyze, count_city, other, charCity, charXueli, charWorkJy, charWorkIndustry, charWorkSize, get_data_list, get_word_view

# 防止不同app中的URL的name产生冲突   reverse(appName:hello)
app_name = 'position'

urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('get_pos/', get_pos, name='get_pos'),
    path('search_key/', search_key_view, name='search_key'),
    path('select_points/', select_points, name='select_points'),
    path('analyze/', analyze, name='analyze'),
    path('count_city/', count_city, name='count_city'),
    path('other/', other, name='other'),
    path('charCity/', charCity, name='charCity'),
    path('charXueli/', charXueli, name='charXueli'),
    path('charWorkJy/', charWorkJy, name='charWorkJy'),
    path('charWorkIndustry/', charWorkIndustry, name='charWorkIndustry'),
    path('charWorkSize/', charWorkSize, name='charWorkSize'),
    path('get_data_list/', get_data_list, name='get_data_list'),
    path('get_word_cloud/', get_word_view, name='get_word_cloud'),
]

lagou_position/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

# 要放在/ 路由  要么你就在把URL 定义成 /admin/media/

urlpatterns = [
    path('', include('apps.position.urls')),
    # path('position/', include('apps.position.urls')),
    path('auth/', include('apps.authPro.urls')),
    path('conn/', include('apps.conn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/authPro/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    email = models.EmailField(max_length=60, unique=True)
    join_date = models.DateTimeField(auto_now_add=True)
    # avatar = models.ImageField(default="avatar/default.jpeg", upload_to='avatar/')   # 头像

    def __str__(self):
        print(self.username)

apps/authPro/forms.py
from django import forms
from django.core import validators
from apps.forms import FormMixin
from utils import mcache
from .models import User


# 自定义验证器
# 多继承
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput())
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput())
    # captcha = forms.CaptchaField(label='验证码')
    # widget = forms.PasswordInput用于指定该字段在form表单里表现为 < input type = 'password' / >，也就是密码输入框
    # graph_captcha = forms.CharField(max_length=4, min_length=4)

    # # 自定义验证   self => form  不通过验证码通过不用保存数据
    # def valid_data(self):
    #     # 验证: 图形验证码
    #     graph_captcha = self.cleaned_data.get('graph_captcha')
    #     server_graph_captcha = mcache.get_key('graph_captcha')
    #     print('graph_captcha')
    #     print(graph_captcha)
    #     print(server_graph_captcha)
    #     if not server_graph_captcha:
    #         # return self.add_error("graph_captcha", "图形验证码已过期")
    #         return False
    #
    #     if graph_captcha.lower() != server_graph_captcha.lower():
    #         # return self.add_error("graph_captcha", "图形验证码不正确")
    #         return False
    #     return True


class RegisterForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput())
    email = forms.EmailField(label="邮箱", widget=forms.EmailInput())
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput())
    password_repeat = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput())
    # captcha = forms.CaptchaField(label='验证码')

apps/authPro/views.py
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout

from apps.authPro.forms import LoginForm, RegisterForm
from utils import restful, mcache
from utils.captcha.captcha import Captcha
import hashlib

from io import BytesIO
from .models import User
from django.db import connection


# 登录
def LoginView(request):
    if request.method == 'GET':
        return render(request, 'authPro/login.html')

    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        message = "请检查填写的内容！"
        # 验证: 图形验证码
        if login_form.is_valid():
            server_graph_captcha = mcache.get_key('graph_captcha')
            graph_captcha = request.POST.get('captcha_graph') # 客户端验证码

            if server_graph_captcha:
                if graph_captcha.lower() == server_graph_captcha.lower():
                    username = request.POST.get('username')
                    password = request.POST.get('password')
                    hash_psd = hash_code(password)
                    # 其他验证
                    try:
                        # user = User.objects.get(username=username)
                        sql = "select * from authPro_user where username='"+ username + "';"
                        # user = User.objects.filter(username=str(username))
                        cursor = connection.cursor()
                        cursor.execute(sql)
                        db_user_tuple = cursor.fetchone()
                        if db_user_tuple[2] == hash_psd:
                            request.session['is_login'] = True
                            request.session['user_id'] = db_user_tuple[0]
                            request.session['user_name'] = db_user_tuple[1]
                            request.session['user_email'] = db_user_tuple[3]
                            request.session['user_jdate'] = str(db_user_tuple[4]).split(".")[0]
                            # request.session['user_avatar'] = user.avatar

                            next_url = request.GET.get("next", '')
                            if next_url:
                                return redirect(next_url)
                            else:
                                return redirect("/")
                        else:
                            message = "密码不正确！"
                    except Exception as e:
                        message = "用户不存在！"
                        print(e)
                else:
                    message = "图形验证不正确"
            else:
                message = "验证码已过期"
        return render(request, 'authPro/login.html', locals())


# 退出登录
def logout_view(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/")
    request.session.flush()   # flush会一次性清空session中所有内容
    return redirect('/auth/login/')


# 注册   next_url的修改
def register_view(request):
    if request.method == "GET":
        return render(request, "authPro/register.html")

    # if request.session.get('is_login', None):
    #     # 登录状态不允许注册。你可以修改这条原则！
    #     return redirect("/")

    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            password_repeat = register_form.cleaned_data['password_repeat']
            email = register_form.cleaned_data['email']
            if password != password_repeat:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'authPro/register.html', locals())
            else:
                same_name_user = User.objects.filter(username=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'authPro/register.html', locals())
                same_email_user = User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'authPro/register.html', locals())

                # 当一切都OK的情况下，创建新用户
                new_user = User()
                new_user.username = username
                new_user.password = hash_code(password)
                new_user.email = email
                new_user.save()
                return redirect('/auth/login/')  # 自动跳转到登录页面
    # register_form = RegisterForm()
    return render(request, 'authPro/register.html', locals())


# 图形验证码
def graph_captcha(request):
    captcha, image = Captcha.gene_code()
    # image 是一个函数对象  要变成一个数据流才能被 HttpResponse 识别
    # BytesIO 用于存放字节流
    # 实例化
    out = BytesIO()
    # 保存图片
    image.save(out, 'png')
    # 设置回到文件最开头
    out.seek(0)
    # 设置类型
    response = HttpResponse(content_type="image/png")
    # 去读文件 并写入response
    response.write(out.read())
    mcache.set_key('graph_captcha', captcha)

    return response


def hash_code(s, salt='mysite'):# 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


# # 编辑头像
# def profile_edit(request, id):
#     if request.method == 'POST':
#         # 上传的文件保存在 request.FILES 中，通过参数传递给表单类
#         profile_form = ProfileForm(request.POST, request.FILES)
#         if profile_form.is_valid():
#


# 关于我
def aboutme_view(request):
    return render(request, "authPro/aboutme.html")


# 修改密码
def updatepsd_view(request):
    new_psd = request.POST.get('newpsd')
    psd = hash_code(new_psd)
    try:
        User.objects.filter(id=request.session.get('user_id')).update(password=psd)
    except Exception as e:
        print(e)
    else:
        print("修改密码成功!")


    return HttpResponse("success")

templates/authPro/aboutme.html
{% extends 'base/base_top.html' %}

{% block title %}  我的资料 {%  endblock %}

{% block link %}
{#    <link rel="stylesheet" href="{% static 'css/authPro/auth.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/authPro/about.css' %}">
{%  endblock %}




{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
{#          <form class='form-me' action="" οnsubmit="return disable_func()">#}
          <div class="form-me">
              <h2 class="text-center">欢迎用户： {{ request.session.user_name }} </h2>

              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username"  value="{{ request.session.user_name }}" readonly="true">
              </div>
              <div class="form-group">
                <label for="id_email">邮箱：</label>
                <input type="text" name='email' class="form-control" id="id_email"  value="{{ request.session.user_email }}" readonly="true">
              </div>
              <div class="form-group">
                <label for="id_data">加入时间：</label>
                <input type="text" name='jdate' class="form-control" id="id_data"  value="{{ request.session.user_jdate }}" readonly="true">
              </div>
              <div class="form-group">
                <label for="id_password">新密码：</label>
                <input type="password" name='password' class="form-control" id="id_password" placeholder="修改密码" >
              </div>
             <div class="form-group">
                <label for="id_password_repeat">确认密码：</label>
                <input type="password" name='password_repeat' class="form-control" id="id_password_repeat" placeholder="确认密码" >
              </div>

              <button class="btn btn-primary pull-left"><a href="{% url 'position:index' %}" style="color: #FFFFFF"> &lt;&lt;&nbsp;返回</a></button>
              <button class="btn btn-primary pull-right" id="update_psd" type="submit">修改密码</button>

          </div>
        </div>
    </div> <!-- /container -->
{% endblock %}







{% block script %}
    <script src="{% static 'js/authPro/about.js' %}"></script>
{% endblock %}

templates/authPro/login.html
{% extends 'base/base_top.html' %}

{% block title %}  登录 {%  endblock %}

{% block link %}
{#    <link rel="stylesheet" href="{% static 'css/authPro/auth.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/authPro/login.css' %}">
{%  endblock %}

{% block header %}
{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-login' action="/auth/login/" method="post">

                {% if message %}
                    <div class="alert alert-warning">{{ message }}
                    <span style="display: inline-block; float: right; cursor:pointer" class="small_x">X</span>
                    </div>
                {% endif %}

              <h2 class="text-center">欢迎登录</h2>

              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_password">密码：</label>
                <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>
              </div>

              <div class="form-group">
                <label for="id_captcha_graph" style="display: block">图形验证码：</label>
                <input type="text" placeholder="验证码" name="captcha_graph" class="form-control form-captcha" id="id_captcha_graph" maxlength="4" style="width: 59%">
                <a href="javascript:void(0);" class="captcha-graph-img">
                  <img src="{% url 'authPro:graph_captcha' %}" alt="验证码" title="点击刷新">
                </a>
              </div>

              <div>
                  <button id="reg" class="btn btn-danger pull-left"><a href="{% url 'authPro:register' %}" style="color: #FFFFFF">注册</a></button>
                  <button type="submit" class="btn btn-primary pull-right">登录</button>
              </div>

          </form>
        </div>
    </div>
{% endblock %}




{% block script %}
    <script src="{% static 'js/authPro/auth.js' %}"></script>
{% endblock %}

templates/authPro/register.html
{% extends 'base/base_top.html' %}

{% block title %}  注册 {%  endblock %}

{% block link %}
{#    <link rel="stylesheet" href="{% static 'css/authPro/auth.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/authPro/register.css' %}">
{%  endblock %}


{% block header %}
{% endblock %}



{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="{% url 'authPro:register' %}" method="post">

                {% if message %}
                    <div class="alert alert-warning">{{ message }}
                    <span style="display: inline-block; float: right; cursor:pointer" class="small_x">X</span>
                    </div>
                {% endif %}

              <h2 class="text-center">欢迎注册</h2>

              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_email">邮箱：</label>
                <input type="text" name='email' class="form-control" id="id_email" placeholder="Email" required>
              </div>
              <div class="form-group">
                <label for="id_password">密码：</label>
                <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>
              </div>
             <div class="form-group">
                <label for="id_password_repeat">确认密码：</label>
                <input type="password" name='password_repeat' class="form-control" id="id_password_repeat" placeholder="Password" required>
              </div>

              <button class="btn btn-danger pull-left"><a href="{% url 'authPro:login' %}" style="color: #FFFFFF">登录</a></button>
              <button type="submit" class="btn btn-primary pull-right">注册</button>

          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}


{% block script %}
    <script src="{% static 'js/authPro/auth.js' %}"></script>
{% endblock %}